### ISSUE TITLE
vhs record command takes me out of zsh and into bash on Mac OS

### ISSUE THREAD

**Issue by citypaul** [charmbracelet/vhs#255]
When I run `vhs record > test`, I'm booted out of `zsh` for some reason into a bash shell:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/5850178/224184781-7eaf9e08-8abd-4514-868e-7b5206ebe341.png">

This isn't just printing a warning message, it's actually putting me into bash, and I lost all access to zsh and my zsh_profile setup, so all aliases and so on stop working.

If it helps, I'm on macOS 13.2.1, zsh 5.8.1 and VHS 0.3.0.

**Comment by basilioss** [comment]
Try to use `vhs record -s zsh > test` instead of `vhs record > test`.

**Comment by picatz** [comment]
FWIW, I also ran into this and was surprised. It seems to happen due to the following:

https://github.com/charmbracelet/vhs/blob/1d202a46b770170420a3c29983d8cd5b0d43d0d6/main.go#L153-L159

`shell` is a variable used by `recordCmd` is defaulted to `bash`:

https://github.com/charmbracelet/vhs/blob/1d202a46b770170420a3c29983d8cd5b0d43d0d6/main.go#L241

`recordCmd` runs the `Record` function, which runs the configured shell from the command-line flag:

https://github.com/charmbracelet/vhs/blob/1d202a46b770170420a3c29983d8cd5b0d43d0d6/record.go#L64-L70

I think we could fix this by using `os.Getenv("SHELL")` or some equivalent instead of defaulting to `bash` in the `recordCmd` flags. Might need a wrapper to `os.Getenv` if `SHELL` isn't actually set? 🤔

**Comment by maaslalani** [comment]
Hey @picatz, that's a great point. We can simply query the default shell of the user and use that. In addition, we can make it so that the record tape file automatically includes the correct `Set Shell` command to ensure these are consistent.

https://github.com/charmbracelet/vhs/pull/279

I originally had it as bash for 2 reasons:
1. So that the user knew that they were in a recording session
2. Bash was the default shell for VHS so feeding the tape directly to VHS would work correctly if the recording was used.

I believe we can set the `PROMPT` later to ` VHS • ` to indicate to the user that we are recording and the `Set Shell` setting would handle the default shell for VHS.

**Comment by maaslalani** [comment]
Fixed by: https://github.com/charmbracelet/vhs/pull/279
