### ISSUE TITLE
Can you please allow for disabling cursor blinking?

### ISSUE THREAD

**Issue by blacktop** [charmbracelet/vhs#319]
I am making some vhs-es for long running commands for a presentation, but don't want people to have to wait forever for it to finish.

I assume there's no way to skip the 'waiting' step? 

I'm currently using `Set Framerate 120` but the cursor blinks like CRAZY and is very distracting.

I'd like a way to disable it (OR a way to skip time where the terminal output doesn't change?)

Thank you!

**Comment by tr3mor** [comment]
I don't like blinks too (since it is not what I am used to in my terminal). I guess it makes sense to remove hardcode from here https://github.com/charmbracelet/vhs/blob/ef4515ddadc0a3cba418db721e5634cb678af524/tty.go#L33 and just move it to Set parameter (similar to other parameters like fontSize) with "true" as default.
I can work on PR but would love to hear the maintainers' opinions on this one.
P.S. If you want it right now, get the source code, update the line above, and just build the new binary.

**Comment by maaslalani** [comment]
Hey, the option, similar to `FontSize` would definitely be accepted as a PR :)

```
Set CursorBlink true
Set CursorBlink false
```

Would be great! I am also happy to PR it myself if you want 😄
