### ISSUE TITLE
Why ttyd is required?

### ISSUE THREAD

**Issue by DocSuma** [charmbracelet/vhs#410]
https://github.com/tsl0922/ttyd

**Comment by maaslalani** [comment]
Hi @DocSuma! `ttyd` is required as a dependency of the project so that we can use browser automation tools to perform actions on the terminal (such as typing, pressing modifier keys, and most importantly screenshot the terminal in a cross-platform way)

VHS launches an instance of `ttyd` then connects to it and begins capturing the frames of the terminal and performing actions via `go-rod` on the browser.

I hope that explains why we need `ttyd`!
