### ISSUE TITLE
case insensitivity

### ISSUE THREAD

**Issue by jake-stewart** [charmbracelet/vhs#413]
**Is your feature request related to a problem? Please describe.**
i find it annoying that i have to type "Sleep 500ms" instead of "sleep 500ms" and can't think of a good reason why it is case sensitive.

**Describe the solution you'd like**
make it case insensitve

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jake-stewart** [comment]
nevermind i see you allow quoteless strings and rely on the capital. adding case insensitivity could break scripts
shame but oh well

**Comment by maaslalani** [comment]
I think its still possible to provide case insensitive keywords since the quoteless strings are the default case if the string matches no other words, so we could also match for the lowercase version of the word.

Although, I think for consistency I personally prefer if all keywords have the same case.
